using LinearAlgebra

#input data (15.4)
IO_Germany_Extentded = [[1131, 7930, 426, 8748, 25675] [25480, 304584, 7334, 183818, 558184] [1, 64167, 3875, 14190, 163373] [2079, 83423, 37908, 106242, 1137535]]
IO_Germany = [[1131, 7930, 426, 8748] [25480, 304584, 7334, 183818] [1, 64167, 3875, 14190] [2079, 83423, 37908, 106242]]
Y = [[15219, 0, 0, 0] [0, 619296, 0, 0] [0, 0, 196063, 0] [0, 0, 0, 1054189]]

#divide each collumn by its sum (15.6)
Input_Coef_Germany = IO_Germany ./ sum(IO_Germany_Extentded, dims=1)

#compute (I-A)^-1 (15.10)
I_Matrix = Matrix(I, 4, 4)
I_A = I_Matrix - Input_Coef_Germany
I_A_INV = inv(I_A)

#emissions data (15.13)
Emissions_Germany_Extended = [[10448, 1534] [558327, 1160] [11194, 1] [107051, 1063] [217137, 136]]
Emissions_Germany = [[10448, 1534] [558327, 1160] [11194, 1] [107051, 1063]]

#compute emissions coefficients
Emissions_Coef_Germany = Emissions_Germany ./ sum(IO_Germany_Extentded, dims=1)

#compute matrix of direct and indirect emissions per unit output B(I - A)^-1 (15.13)
B_I_A_INV = Emissions_Coef_Germany * I_A_INV

#compute the emission content of final demand
Z = B_I_A_INV * Y

#1
Input_Coef_Germany
#= 
(2, 4) of this matrix represents Industry's share of Services cost of goods
(4, 2) of this matrix represents Services' share of Industry's cost of goods
=#


#2
I_A_INV
#= 
(2, 4) of this matrix represents Industry's share of Services' value added in direct and indirect effects
(4, 2) of this matrix represents Services' share of Industry's value added in direct and indirect effects
=#

#3
Emissions_Coef_Germany
#= 
(2, 3) of this matrix represents Methane Emissions from Construction
=#

#4
B_I_A_INV
#=
(2, 3) of this matrix reprents the methane emissions from construction per unit of output. 
=#

#5
Z

#6
#= 
Doing a piecewise comparison of any entry of E(x, y) and Z(x, y) will show you the difference between direct emissions (in the case of E)
whereas Z shows how much emission content of final demand is attributabal to each sector. In essence, by demanding products (inputs)
from other sectors you are indirectly contributing to their emissions (E). Matrix Z shows how much of total emissions (E) can not be 
attributed to the demand of a sector or how much extra emissions are generated by the demand of a sector. Using this information
we can directly attribute emissions across the total economy of one sector and attribute the emissions to them and their demand for 
emissions in the broader economy. 
=#